export const nationalities = [
    { code: "ZAF", name: "South Africa" },
    { code: "GBR", name: "United Kingdom" },
    { code: "USA", name: "United States" },
    { code: "CAN", name: "Canada" },
    { code: "AUS", name: "Australia" },
    { code: "DEU", name: "Germany" },
    { code: "FRA", name: "France" },
    { code: "ITA", name: "Italy" },
    { code: "ESP", name: "Spain" },
    { code: "NLD", name: "Netherlands" },
    { code: "BEL", name: "Belgium" },
    { code: "PRT", name: "Portugal" },
    { code: "SWE", name: "Sweden" },
    { code: "NOR", name: "Norway" },
    { code: "DNK", name: "Denmark" },
    { code: "FIN", name: "Finland" },
    { code: "ISL", name: "Iceland" },
    { code: "CHE", name: "Switzerland" },
    { code: "AUT", name: "Austria" },
    { code: "HUN", name: "Hungary" },
    { code: "POL", name: "Poland" },
    { code: "ROU", name: "Romania" },
    { code: "BGR", name: "Bulgaria" },
    { code: "CRO", name: "Croatia" },
    { code: "CZE", name: "Czech Republic" },
    { code: "EST", name: "Estonia" },
    { code: "HKG", name: "Hong Kong" },
    { code: "IND", name: "India" },
    { code: "JPN", name: "Japan" },
    { code: "KOR", name: "South Korea" },
    { code: "LTU", name: "Lithuania" },
    { code: "LUX", name: "Luxembourg" },
    { code: "LVA", name: "Latvia" },
    { code: "MEX", name: "Mexico" },
    { code: "MYS", name: "Malaysia" },
    { code: "MNE", name: "Montenegro" },
    { code: "NGA", name: "Nigeria" },
    { code: "NZL", name: "New Zealand" },
    { code: "PHL", name: "Philippines" },
    { code: "SAU", name: "Saudi Arabia" },
    { code: "SVK", name: "Slovakia" },
    { code: "SVN", name: "Slovenia" },
    { code: "TUR", name: "Turkey" },
    { code: "UKR", name: "Ukraine" },
    { code: "URY", name: "Uruguay" },
    { code: "VAT", name: "Vatican City" },
    { code: "VEN", name: "Venezuela" },
    { code: "ZWE", name: "Zimbabwe" },
    { code: "ARG", name: "Argentina" },
    { code: "BRA", name: "Brazil" },
    { code: "CHL", name: "Chile" },
    { code: "CHN", name: "China" },
    { code: "COL", name: "Colombia" }
  ];